version: '3.3'
services:
  pg:
    image: postgres:9.6
    container_name: "postgres"
    environment:
      - POSTGRES_DB=cp_scraper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432